export enum TemplatesRegisters {
    EXPORT_CATALOG_LIST = 'PRINT_CATALOG_LIST', //IMPRESION DE CATALOGOS
    EXPORT_CATALOG_REFERENCES = 'PRINT_CATALOG_LIST_REFERENCES', //IMPRESION DE CATALOGO CON REFERENCIAS
    PRINT_ORDER = 'PRINT_ORDER', //IMPRESION DE ORDENES
};
