version: '3.5'

networks:
  app-tier-migration:
    external:
      name: app-tier-shared

services:
  migration:
    image: 'rolmos/moie-lucy-api:${APP_VERSION}'
    command: 'npm run start'
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "8086:8086"
    networks:
      - app-tier-migration
    environment:
      PORT: 8086
      HOST: ${HOST}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      SEED_DB: ${SEED_DB}
      DIAN_USER: ${DIAN_USER}
      DIAN_PASSWORD: ${DIAN_PASSWORD}
      PUBLIC_URL: ${PUBLIC_URL}
      TZ: America/Bogota
