export const services = {
    Bill: 'BillService',
    BillConfig: 'BillConfigService',
    BillCreditMemo: 'BillCreditMemoService',
    Category: 'CategoryService',
    Customer: 'CustomerService',
    CommentCustomer: 'CommentCustomerService',
    CommentOrder: 'CommentOrderService',
    CommentPostSale: 'CommentPostSaleService',
    DeliveryLocality: 'DeliveryLocalityService',
    Municipality: 'MunicipalityService',
    Office: 'OfficeService',
    Order: 'OrderService',
    OrderDetail: 'OrderDetailService',
    OrderHistoric: 'OrderHistoricService',
    Payment: 'PaymentService',
    Product: 'ProductService',
    ProductImage: 'ProductImageService',
    ProductSize: 'ProductSizeService',
    Size: 'SizeService',
    State: 'StateService',
    User: 'UserService',
    Movement: 'MovementService',
    Attachment: 'AttachmentService',
};
