export const EXPORTER_INTERRAPIDISIMO_CD = 'EXPORTER_INTERRAPIDISIMO_CD';
export const EXPORTER_POSTVENTA = 'EXPORTER_POSTVENTA';
export const EXPORTER_ELECTRONIC_BILL = 'EXPORTER_ELECTRONIC_BILL';
export const EXPORTER_CONCILIATES = 'EXPORTER_CONCILIATES';
export const EXPORTER_OFFICES = 'EXPORTER_OFFICES';
